### ISSUE TITLE
Error: file_get_contents(https://www.habbo.com//gamedata/furnidata_xml/0): failed to open stream: HTTP request failed! HTTP/1.1 463 

### ISSUE THREAD

**Issue by xJuice** [sant0ro/habbo-asset-extractor#3]
Error: file_get_contents(https://www.habbo.com//gamedata/furnidata_xml/0): failed to open stream: HTTP request failed! HTTP/1.1 463 

i use http and https no work.

all extensions enabled

php 5.6

**Comment by sant0ro** [comment]
First remove the double //
Second remove the HTTPS.
