### ISSUE TITLE
Error: file_get_contents(http://habbo.nl/gamedata/furnidata_xml/0): failed to open stream: HTTP request failed! HTTP/1.1 463 

### ISSUE THREAD

**Issue by xJuice** [sant0ro/habbo-asset-extractor#4]
Error: file_get_contents(http://habbo.nl/gamedata/furnidata_xml/0): failed to open stream: HTTP request failed! HTTP/1.1 463 

why you closed my issue ?

**Comment by xJuice** [comment]
Habbo SWF Furniture resource dump Tool

OFFICIAL RESOURCE URL : http://habbo.nl

FLASH CLIENT URL      : http://habboo-a.akamaihd.net/gordon/PRODUCTION-201506301513-456128588/

OUTPUT PATH           : D:\inetpub\wwwroot\habbo-asset-extractor-master/download/

DCR URL               : http://habboo-a.akamaihd.net/dcr/hof_furni/

**Comment by xJuice** [comment]
Habbo SWF Furniture resource dump Tool
    OFFICIAL RESOURCE URL : http://www.habbo.com
    FLASH CLIENT URL      : http://habboo-a.akamaihd.net/gordon/PRODUCTION-201512170847-152005991/
    OUTPUT PATH           : D:\inetpub\wwwroot\habbo-asset-extractor-master/download/
    DCR URL               : http://habboo-a.akamaihd.net/dcr/hof_furni/
   

 Extract FurniData

    Download: http://www.habbo.com/gamedata/furnidata_xml/0

    Connected...

    Mime-type: text/html

    Filesize: 6597

    Error: file_get_contents(http://www.habbo.com/gamedata/furnidata_xml/0): failed to open stream: HTTP request failed! HTTP/1.1 463 

    Notice: Trying to get property of non-object in D:\inetpub\wwwroot\habbo-asset-extractor-master\assets.php on line 210 Warning: Invalid argument supplied for foreach() in D:\inetpub\wwwroot\habbo-asset-extractor-master\assets.php on line 210 Notice: Trying to get property of non-object in D:\inetpub\wwwroot\habbo-asset-extractor-master\assets.php on line 220 Warning: Invalid argument supplied for foreach() in D:\inetpub\wwwroot\habbo-asset-extractor-master\assets.php on line 220

    Starting RoomTypes

    Starting WallTypes

    update complete.

**Comment by sant0ro** [comment]
http://www.habbo.com/gamedata/furnidata_xml/1a82719e4dc9913d3b605547098b5211d3319e36

Please put absolute url.
